#!/bin/sh

# this script is intended to be used with i3status
# it takes two time intervals and corresponding messages
# it alternates the two messages for the given time intervals
# and adds that to i3status output. also takes color of text

# usage, i3status | /this/file T1 T1_MESSAGE T2 T2_MESSAGE COLOR
# format must be i3bar in i3status conf

T1="$1"
T1_MESSAGE="$2"
T2="$3"
T2_MESSAGE="$4"
COLOR="$5"

# amazing bash builtin
SECONDS=0

curr=$SECONDS
diff=0
counter=0
state="$T1_MESSAGE"
function update_status {
	curr=$SECONDS
	diff=$((curr-last))
	counter=$((counter+diff))
	if [ "$state" == "$T2_MESSAGE" ] && [ "$counter" -ge "$T2" ]; then
		state="$T1_MESSAGE"
		counter=0
	elif [ "$state" == "$T1_MESSAGE" ] && [ "$counter" -ge "$T1" ]; then
		state="$T2_MESSAGE"
		counter=0
	fi
	last=$curr
}

read line && echo "$line" && read line && echo "$line" && while :
do
	read line
	update_status
	dat="$state"
	dat="[{ \"full_text\": \"${dat}\", \"color\": \"${COLOR}\", \"markup\": \"none\" },"
	echo "${line/[/$dat}" || exit 1
done
